customize-design:
  - 'wai-customize-design'
shared-experiences:
  - 'wai-shared-experiences'
intro-act:
  - 'wai-intro-act'
intro-earl:
  - 'wai-intro-earl'
combined-expertise:
  - 'wai-combined-expertise'
inclusion:
  - 'wai-inclusion'
wcag-mob-overlap:
  - 'wai-wcag-mob-overlap'