language: ruby
rvm:
  - 2.4.1

before_script:
- chmod +x ./script/cibuild-preview.sh # or do this locally and commit
- chmod +x ./script/cibuild-live.sh # or do this locally and commit

# Assume bundler is being used, therefore
# the `install` step will run `bundle install` by default.
# script: ./script/cibuild.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master     # test the gh-pages branch

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation

sudo: false # route your build to the container-based infrastructure for a faster build

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

jobs:
  include:
    - stage: deploy
      script: ./script/cibuild-preview.sh
      deploy: &preview
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        target-branch: gh-pages
        local-dir: _site
        on:
          branch: master
    - stage: deploy
      script: ./script/cibuild-live.sh
      deploy: &live
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep-history: true
        target-branch: live
        local-dir: _site
        on:
          branch: master