# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"
# Build settings
markdown: kramdown
repository: w3c/wai-website

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

includes_dir: _external/wai-website-jekyll-templates/_includes
layouts_dir: _external/wai-website-jekyll-templates/_layouts

collections:
  perspective-videos:
    area: "Accessibility Fundamentals"
    name: "Web Accessibility Perspective Videos"
    shortname: "Perspective Videos"
    icon: "book" # TODO
    repostitory: w3c/wai-showcase-examples
    output: true
    acknowledgements: true
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"