# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Web Accessibility Initiative (WAI)"
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  The Website of the World Wide Web Consortium’s Web Accessibility Initiative.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter:
  username: w3c_wai
author: w3c_wai
exclude:
  - "_external"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "w3c.json"
# Build settings
markdown: kramdown
kramwdown:
  toc_levels: 2..3
  input: GFM
  syntax_highlighter: rouge
highlighter: rouge
repository: w3c/wai-website

ytkey: AIzaSyCiZ9uToWu9jb7BTx47NtzCvmGGXKXp8nI

includes_dir: _external/wai-website-jekyll-templates/_includes
layouts_dir: _external/wai-website-jekyll-templates/_layouts

collections:
  perspective-videos:
    area: "Accessibility Fundamentals"
    name: "Web Accessibility Perspective Videos"
    shortname: "Perspective Videos"
    icon: "book" # TODO
    repostitory: w3c/wai-showcase-examples
    output: true
    acknowledgements: true
    permalink: /:collection/:path/
  people-use-web:
    area: "Accessibility Fundamentals"
    name: "How People with Disabilities Use the Web"
    icon: "book" # TODO
    repostitory: w3c/wai-people-use-web
    output: true
    acknowledgements: false
    permalink: /:collection/:path/
  planning-and-managing:
    area: "Plan and Manage"
    name: "Planning and Managing Web Accessibility"
    icon: "book" # TODO
    repostitory: w3c/wai-dynamic-planning
    output: true
    acknowledgements: false
    permalink: /:collection/:path/
  tutorials:
    area: "Design & Develop"
    name: "Web Accessibility Tutorials"
    shortname: Tutorials
    icon: "book" # TODO
    repostitory: w3c/wai-tutorials
    output: true
    acknowledgements: false
    permalink: /:collection/:path/
    groups:
      - name: index # Note: index is a magic word, it links to the index of the resource
        title: Overview
      - name: page-structure
        title: Page Structure
      - name: menus
        title: Menus
      - name: images
        title: Images
      - name: tables
        title: Tables
      - name: forms
        title: Forms
      - name: carousels
        title: Carousels
  accessibility-training:
    area: "Teach & Advocate"
    name: "Accessibility Training"
    shortname: Trainings
    icon: "book" # TODO
    repostitory: w3c/wai-tbd
    output: true
    acknowledgements: false
    permalink: /teach-advocate/:collection/:path/
  tips:
    area: "All Areas"
    name: "Tips for Getting Started"
    shortname: Getting Started Tips
    icon: "book" # TODO
    repostitory: w3c/wai-quick-start
    output: true
    acknowledgements: false
    permalink: /:collection/:path/
  policies:
    area: "Plan & Manage"
    name: "Web Accessibility Laws & Policies"
    shortname: "Laws & Policies"
    icon: "book" # TODO
    repostitory: w3c/wai-tbd
    output: true
    acknowledgements: false
    permalink: /:collection/:path/

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "_perspective-videos"
    values:
      layout: "sidenav"
  -
    scope:
      path: "_people-use-web"
    values:
      layout: "sidenav"
  -
    scope:
      path: "_planning-and-managing"
    values:
      layout: "sidenav"
  -
    scope:
      path: "_tutorials"
    values:
      layout: "sidenav"
  -
    scope:
      path: "_accessibility-training"
    values:
      layout: "sidenav"
  -
    scope:
      path: "_tips"
    values:
      layout: "sidenav"
  -
    scope:
      path: "_policies"
    values:
      layout: "policy"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-relative-links
  - jekyll-redirect-from

relative_links:
  -  enabled:     true
  -  collections: true

incremental: true