[build]
# with debugging: command = "git submodule update --init --remote && bundle exec jekyll build --verbose --trace --config '_config.yml,_config_staging.yml'"
command = "git submodule update --init --remote && npm install && bundle exec jekyll build --trace --config '_config.yml,_config_staging.yml'"
publish = "_site"

[build.environment]
RUBY_VERSION = "2.6.2" 

[context.production]
# We don't need this but it means will test the full URL access to forms function
environment = { JEKYLL_ENV = "production" }

[[redirects]]
  from = "/wai-website"
  to = "/"
  status = 404

[dev]
publish = "_site"
framework = "#static"

[functions]
directory = "_functions"
node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
