[build]
command = "git submodule update --init --remote && bundle exec jekyll build --trace --config '_config.yml,_config_staging.yml'"
publish = "_site"

[build.environment]
RUBY_VERSION = "2.6.2" 

[[redirects]]
  from = "/wai-website"
  to = "/"
  status = 404

[dev]
publish = "_site"
framework = "#static"
