name: Add Resource

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Resource Name'     
        required: true
        default: 'wai-about-wai'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name Adding resource submodule: {{ github.event.inputs.resource }}
      run: |
        [ -d _external/resources/$WAI_NEW_RESOURCE ] && echo "Resource $WAI_NEW_RESOURCE exists" && exit 1
        git submodule update --init --remote
        git submodule add https://github.com/w3c/$WAI_NEW_RESOURCE.git _external/resources/$WAI_NEW_RESOURCE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WAI_NEW_RESOURCE: ${{ github.event.inputs.resource }}
    - name echo "Linking in resource: {{ github.event.inputs.resource }}
      run: |
        ln -s _external/resources/$WAI_NEW_RESOURCE/content pages/$WAI_NEW_RESOURCE
        ln -s _external/resources/$WAI_NEW_RESOURCE/content-images/$WAI_NEW_RESOURCE content-images/$WAI_NEW_RESOURCE
      env:
        WAI_NEW_RESOURCE: ${{ github.event.inputs.resource }}
    - name: commit changed files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Action "Add Resource" added ${{ github.event.inpts.resource }}
        branch: master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WAI_NEW_RESOURCE: ${{ github.event.inputs.resource }}
      

    
