name: Add Resource

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Resource Name'     
        required: true
        default: 'wai-about-wai'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "Linking in resource: $WAI_NEW_RESOURCE"
        [ -d _external/resources/$WAI_NEW_RESOURCE ] && echo "Resource //$WAI_NEW_RESOURCE exists." && exit 1
      env:
        WAI_NEW_RESOURCE: ${{ github.event.inputs.resource }}
    - uses: actions/checkout@v2.3.4
      with:
        submodules: true
    - run: |
        echo git submodule update --remote
        echo "Linking in resource: $WAI_NEW_RESOURCE"
        echo git submodule add https://github.com/w3c/$WAI_NEW_RESOURCE.git _external/resources/$WAI_NEW_RESOURCE
        echo ln -s _external/resources/$WAI_NEW_RESOURCE/content pages/$WAI_NEW_RESOURCE
        echo ln -s _external/resources/$WAI_NEW_RESOURCEcontent-images/$WAI_NEW_RESOURCE content-images/$WAI_NEW_RESOURCE
      env:
        WAI_NEW_RESOURCE: ${{ github.event.inputs.resource }}
    - name: commit changed files
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Apply automatic changes - added resource ${{ github.event.inputs.resource }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WAI_NEW_RESOURCE: ${{ github.event.inputs.resource }}
      

    
