name: AddResource

on:
  workflow_dispatch:
    inputs:
      resource:
        description: 'Resource Name'     
        required: true
        default: 'wai-about-wai'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: |
        echo "Linking in resource: ${{ github.event.inputs.resource }} $ZZZ"
      env: ZZZ: hello

    
