name: Ruby

on:
  release

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Update Externals
      run: |
        git submodule init
        git submodule update --remote
#    - name: commit changed files
#      uses: stefanzweifel/git-auto-commit-action@v2.1.0
#      with:
#        commit_message: Apply automatic changes
#        branch: ${{ github.head_ref }}
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and test with Jekyll
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec jekyll build --config "_config.yml,_config_prod.yml" --profile
#    - name: Zip Files
#      uses: montudor/action-zip@v0.1.0
#      args: zip -r build.zip ./_site"
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: _site
        asset_name: build
        tag: ${{ github.ref }}
        overwrite: true
