# Warning this hides checkouts from the Github commits view
# So unless you record a latter ref you will not be able to revert to the pre rollback state

name: Rollback Website

on:
  workflow_dispatch:
    inputs:
      targetRef:
        description: 'The git ref to roll back too (Hint: Use the "clipboard" icon on right of commits list and then paste)'
        required: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
        fetch-depth: 10
    - name: Rollback
      run: |
        git reset --hard ${{ github.event.inputs.targetRef }}
        git push -f
